### ISSUE TITLE
Missing `\bibliofont` macro

### ISSUE THREAD

**Issue by andrejbauer** [CRCLJournal/crclart#1]
You are using the ACM cictation style in Bibtex, but that one assumes the existence of `\bibliofont`, which seems to be undefined, see this [TeX.SE answer](https://tex.stackexchange.com/questions/655024/undefined-control-sequence-bibfont-bibliofont-footnotesize-when-using-biblat). Would it make sense to define `\bibliofont`?

**Comment by denismerigoux** [comment]
Thanks for reporting @andrejbauer!
